### ISSUE TITLE
Profiles for Flagship paper

### ISSUE THREAD

**Issue by brianherb** [nemoarchive/analytics#136]
We will create three profiles to support the Flagship paper:

- [ ] Transcriptomic / Epigenetic data (Fig2) - [Issue 137](https://github.com/nemoarchive/analytics/issues/137)

- [ ] Merfish data (Fig3) - [Issue 135](https://github.com/nemoarchive/analytics/issues/135)

- [ ] Patchseq data (Fig4) - [Issue 138](https://github.com/nemoarchive/analytics/issues/138)

**Comment by brianherb** [comment]
Profiles completed
